#!/usr/bin/env bash

# bash completion for SBT Version Manager (SVM)

__svm_generate_completion()
{
  declare current_word
  current_word="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "$1" -- "$current_word"))
  return 0
}

__svm_commands ()
{
  declare current_word
  declare command

  current_word="${COMP_WORDS[COMP_CWORD]}"

  COMMANDS='\
    help install uninstall use\
    run ls list deactivate alias\
    unalias copy-packages clear-cache version'

    if [ ${#COMP_WORDS[@]} == 4 ]; then

      command="${COMP_WORDS[COMP_CWORD-2]}"
      case "${command}" in
      alias)  __svm_installed_nodes ;;
      esac

    else

      case "${current_word}" in
      -*)     __svm_options ;;
      *)      __svm_generate_completion "$COMMANDS" ;;
      esac

    fi
}

__svm_options ()
{
  OPTIONS=''
  __svm_generate_completion "$OPTIONS"
}

__svm_installed_nodes ()
{
  __svm_generate_completion "$(svm_ls) $(__svm_aliases)"
}

__svm_aliases ()
{
  declare aliases
  aliases=""
  if [ -d $SVM_DIR/alias ]; then
    aliases="`cd $SVM_DIR/alias && ls`"
  fi
  echo "${aliases}"
}

__svm_alias ()
{
  __svm_generate_completion "$(__svm_aliases)"
}

__svm ()
{
  declare previous_word
  previous_word="${COMP_WORDS[COMP_CWORD-1]}"

  case "$previous_word" in
  use|run|ls|list|uninstall) __svm_installed_nodes ;;
  alias|unalias)  __svm_alias ;;
  *)              __svm_commands ;;
  esac

  return 0
}

complete -o default -o nospace -F __svm svm
